# Source image
FROM node:22-bookworm

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && \
    # apt-get install -y ffmpeg && \
    rm -rf /var/lib/apt/lists/*

# Copy package manifests and install dependencies
COPY package*.json yarn.lock prisma tsconfig*.json ./

RUN yarn install --frozen-lockfile

# Copy the rest of the application
COPY . .

# Expose the app port
EXPOSE 8000

# Start the application in development mode
CMD ["yarn", "start:debug"]